apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini-site-rvt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RSidarte/mini-site-rvt.git
    targetRevision: HEAD
    path: . # car les manifests sont à la racine du repo
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
