name: Build, Push & Sync ArgoCD

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: sidarte
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sidarte/site-homepage:latest

      - name: Sync ArgoCD App
        run: |
          RESPONSE=$(curl -k -X POST https://argo.labaky.fr/api/v1/applications/homepage/sync \
            -H "Authorization: Bearer $ARGOCD_TOKEN")
          echo "ArgoCD Sync Response: $RESPONSE"
        env:
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_BEARER_TOKEN }}
